name: Daily Link Update

on:
  schedule:
    # Berjalan setiap hari jam 00:00 WIB (17:00 UTC)
    - cron: '0 17 * * *'
  workflow_dispatch: # Memungkinkan kamu menjalankan manual untuk ngetes

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Links in index.html
        run: |
          # Ganti link MBG (Lama -> Baru)
          sed -i 's|https://sfl.gl/3gGzv|https://sfl.gl/0ybIxW|g' index.html
          
          # Ganti link Desa Rayap (Lama -> Baru)
          sed -i 's|https://sfl.gl/Xevon|https://sfl.gl/gWdlBl|g' index.html

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Auto update script keys $(date)" || echo "No changes to commit"
          git push
